name: Canary Deployment Evaluation

on:
  schedule:
    # Run evaluation every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  evaluate-canary:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run canary evaluation
        run: node scripts/canary-evaluator.js
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_PROJECT_ID: ${{ secrets.POSTHOG_PROJECT_ID }}
      
      - name: Commit updated configuration if changed
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add config/canary-config.json
          git diff --staged --quiet || git commit -m "Update canary configuration based on metrics [skip ci]"
          git push origin ${GITHUB_REF#refs/heads/}