name: Deploy with secrets

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Replace API keys in config
        run: |
          sed -i 's/__POSTHOG_API_KEY__/${{ secrets.POSTHOG_API_KEY }}/g' config/canary-config.json
          sed -i 's/__POSTHOG_PROJECT_ID__/${{ secrets.POSTHOG_PROJECT_ID }}/g' config/canary-config.json
      
      # Continue with your deployment steps
